version: '3.7'

volumes:
  pg_project:

services:
  pg_db:
    image: postgres
    restart: always
    environment:
      - POSTGRES_PASSWORD=9mREsvXDs9Gk89Ef
      - POSTGRES_USER=postgres
      - POSTGRES_DB=dbname
    volumes:
      - pg_project:/var/lib/postgresql/data
    ports:
      - 5432:5432